using System.Runtime.CompilerServices;

// Version attributes are generated by MSBuild from the shared Version in
// src/Directory.Build.props (GenerateAssemblyInfo=true). Only the attributes
// MSBuild does not generate live here.
[assembly: InternalsVisibleTo( "nresx.Core.Tests" )]
