<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <IsPackable>false</IsPackable>

    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.7.1" />
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\nresx.Core\nresx.Core.csproj" />
  </ItemGroup>

  <Target Name="CopyTestFixtures" BeforeTargets="PreBuildEvent">
    <ItemGroup>
      <_TestFiles Include="$(MSBuildThisFileDirectory)..\..\.test_files\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(_TestFiles)"
          DestinationFiles="@(_TestFiles->'$(TargetDir).test_files\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
  </Target>

</Project>
